USE ai_interviewer;

-- CSS 200 MCQs
-- Source: Pasted markdown(1).md
-- Difficulty mapping (source did not specify difficulty): Q1-50 = Easy, Q51-150 = Medium, Q151-200 = Hard.
-- Reviewed corrections: Q132, Q136, Q140, Q195, Q199.

INSERT INTO questions
(skill, question, option_a, option_b, option_c, option_d, correct_answer, difficulty, explanation)
VALUES
('CSS', 'What does CSS stand for?', 'Computer Style Sheets', 'Cascading Style Sheets', 'Creative Style Syntax', 'Colorful Style Sheets', 'B', 'Easy', 'CSS stands for Cascading Style Sheets and is used to style HTML documents.'),
('CSS', 'What is the main purpose of CSS?', 'Create databases', 'Structure webpage content', 'Style and layout webpage content', 'Write server-side programs', 'C', 'Easy', 'CSS controls the presentation, layout, colors, fonts, and appearance of webpages.'),
('CSS', 'Which HTML tag is used to write internal CSS?', '\\<css>', '\\<style>', '\\<script>', '\\<design>', 'B', 'Easy', 'Internal CSS is written inside the \\<style> element.'),
('CSS', 'Which HTML tag is used to connect an external CSS file?', '\\<css>', '\\<style>', '\\<link>', '\\<stylesheet>', 'C', 'Easy', 'The \\<link> element is used to reference an external stylesheet.'),
('CSS', 'Which attribute is used for inline CSS?', 'css', 'style', 'class', 'design', 'B', 'Easy', 'Inline CSS is written using the style attribute.'),
('CSS', 'Which CSS property changes text color?', 'font-color', 'text-color', 'color', 'foreground', 'C', 'Easy', 'The color property sets the foreground/text color.'),
('CSS', 'Which property changes the background color?', 'background-color', 'bg-color', 'color-background', 'background', 'A', 'Easy', 'background-color specifies an element''s background color.'),
('CSS', 'Which property changes the font size?', 'text-size', 'font-size', 'size', 'font-height', 'B', 'Easy', 'font-size controls the size of text.'),
('CSS', 'Which property changes the typeface?', 'font-family', 'font-type', 'text-family', 'typeface', 'A', 'Easy', 'font-family specifies the font used for text.'),
('CSS', 'Which property makes text bold?', 'font-style', 'font-weight', 'text-bold', 'font-bold', 'B', 'Easy', 'font-weight controls the thickness of text.'),
('CSS', 'Which value commonly makes text bold?', 'strong', 'heavy', 'bold', 'thick', 'C', 'Easy', 'font-weight: bold makes text bold.'),
('CSS', 'Which property makes text italic?', 'font-style', 'font-weight', 'text-style', 'italic-text', 'A', 'Easy', 'font-style: italic displays text in italics.'),
('CSS', 'Which CSS property controls text alignment?', 'text-position', 'text-align', 'align-text', 'font-align', 'B', 'Easy', 'text-align controls horizontal alignment of inline content within a block.'),
('CSS', 'Which value centers text?', 'middle', 'center', 'central', 'align-center', 'B', 'Easy', 'text-align: center centers text.'),
('CSS', 'Which property controls the space between lines?', 'line-height', 'line-spacing', 'text-spacing', 'row-height', 'A', 'Easy', 'line-height controls the height of a line box.'),
('CSS', 'Which property controls spacing between letters?', 'letter-spacing', 'character-spacing', 'text-spacing', 'font-spacing', 'A', 'Easy', 'letter-spacing adjusts the horizontal spacing between characters.'),
('CSS', 'Which property controls spacing between words?', 'word-spacing', 'text-spacing', 'word-gap', 'letter-spacing', 'A', 'Easy', 'word-spacing controls the space between words.'),
('CSS', 'Which property changes text to uppercase/lowercase?', 'text-transform', 'text-case', 'font-transform', 'case-style', 'A', 'Easy', 'text-transform can convert text to uppercase, lowercase, or capitalize it.'),
('CSS', 'Which value makes all letters uppercase?', 'upper', 'uppercase', 'capital', 'upper-case', 'B', 'Easy', 'text-transform: uppercase converts letters to uppercase.'),
('CSS', 'Which value makes all letters lowercase?', 'lowercase', 'lower', 'smallcase', 'lower-case-text', 'A', 'Easy', 'text-transform: lowercase converts letters to lowercase.'),
('CSS', 'Which value capitalizes the first letter of each word?', 'capitalize', 'capital', 'first-letter', 'title-case', 'A', 'Easy', 'capitalize transforms the first letter of each word to uppercase.'),
('CSS', 'Which CSS selector selects all \\<p> elements?', '.p', '#p', 'p', '*p', 'C', 'Easy', 'An element selector selects all elements of that type.'),
('CSS', 'Which selector selects an element by its ID?', '.id', '#id', 'id', '*id', 'B', 'Easy', '# is used to select an element by its ID.'),
('CSS', 'Which selector selects elements by class?', '#class', '.class', 'class', '@class', 'B', 'Easy', '. is the class selector.'),
('CSS', 'Which selector selects every element?', 'all', '#', '.', '*', 'D', 'Easy', 'The universal selector * selects all elements.'),
('CSS', 'Which selector has the highest specificity?', 'Element selector', 'Class selector', 'ID selector', 'Universal selector', 'C', 'Easy', 'An ID selector has higher specificity than class and element selectors.'),
('CSS', 'How is a CSS comment written?', '// comment', '\\<!-- comment -->', '/* comment */', '# comment', 'C', 'Easy', 'CSS comments use /* ... */.'),
('CSS', 'Which property adds space inside an element''s border?', 'margin', 'padding', 'spacing', 'inside-space', 'B', 'Easy', 'Padding is the space between content and the border.'),
('CSS', 'Which property adds space outside an element''s border?', 'padding', 'margin', 'outside-space', 'border-spacing', 'B', 'Easy', 'Margin creates space outside the border.'),
('CSS', 'Which property sets the border?', 'outline', 'border', 'line', 'box-line', 'B', 'Easy', 'The border property controls an element''s border.'),
('CSS', 'Which property sets the width of an element?', 'element-width', 'width', 'size-width', 'horizontal-size', 'B', 'Easy', 'width specifies the width of an element''s box.'),
('CSS', 'Which property sets the height?', 'height', 'element-height', 'vertical-size', 'size', 'A', 'Easy', 'height specifies an element''s height.'),
('CSS', 'Which property rounds element corners?', 'corner-radius', 'border-radius', 'radius', 'round-border', 'B', 'Easy', 'border-radius creates rounded corners.'),
('CSS', 'Which property adds a shadow around a box?', 'box-shadow', 'element-shadow', 'shadow-box', 'border-shadow', 'A', 'Easy', 'box-shadow adds one or more shadows around an element''s box.'),
('CSS', 'Which property adds a shadow to text?', 'font-shadow', 'text-shadow', 'word-shadow', 'letter-shadow', 'B', 'Easy', 'text-shadow adds shadows to text.'),
('CSS', 'Which property controls transparency?', 'opacity', 'transparent', 'visibility', 'alpha-level', 'A', 'Easy', 'opacity controls the transparency of an element and its contents.'),
('CSS', 'What is the valid range of opacity?', '0 to 10', '0 to 100', '0 to 1', '1 to 10', 'C', 'Easy', 'Opacity is represented from 0 (fully transparent) to 1 (fully opaque).'),
('CSS', 'Which property controls an element''s visibility?', 'display', 'visibility', 'visible-state', 'show', 'B', 'Easy', 'visibility controls whether an element is visible while generally preserving its layout space.'),
('CSS', 'Which value hides an element while preserving its layout space?', 'display: none', 'visibility: hidden', 'hidden: true', 'opacity: none', 'B', 'Easy', 'visibility: hidden hides the element but keeps its layout space.'),
('CSS', 'Which value removes an element from the layout?', 'visibility: hidden', 'display: none', 'opacity: 0', 'hidden: true', 'B', 'Easy', 'display: none removes the element from the layout.'),
('CSS', 'Which property controls how an element is displayed?', 'display', 'position', 'layout', 'element-type', 'A', 'Easy', 'The display property controls an element''s box type and layout behavior.'),
('CSS', 'What is the default display value of a \\<div>?', 'inline', 'block', 'flex', 'grid', 'B', 'Easy', '\\<div> is a block-level element by default.'),
('CSS', 'What is the default display value of a \\<span>?', 'block', 'inline', 'flex', 'grid', 'B', 'Easy', '\\<span> is inline by default.'),
('CSS', 'Which display value makes an element inline but allows width and height?', 'inline', 'block', 'inline-block', 'flex-inline', 'C', 'Easy', 'inline-block participates inline while accepting width and height.'),
('CSS', 'Which CSS property controls element positioning?', 'position', 'location', 'place', 'coordinate', 'A', 'Easy', 'position controls how an element is positioned.'),
('CSS', 'Which is a valid CSS position value?', 'fixed', 'locked', 'attached', 'screen', 'A', 'Easy', 'fixed is one of the valid position values.'),
('CSS', 'Which position value keeps an element in the normal flow and allows offsets?', 'absolute', 'relative', 'fixed', 'static-offset', 'B', 'Easy', 'position: relative keeps the element in normal flow and allows positional offsets.'),
('CSS', 'Which position value removes an element from normal flow and positions it relative to a containing block?', 'relative', 'absolute', 'static', 'inline', 'B', 'Easy', 'Absolutely positioned elements are removed from normal flow.'),
('CSS', 'Which position value keeps an element attached to the viewport?', 'absolute', 'fixed', 'relative', 'static', 'B', 'Easy', 'position: fixed positions an element relative to the viewport in the usual case.'),
('CSS', 'Which is the default position value?', 'relative', 'absolute', 'static', 'fixed', 'C', 'Easy', 'Elements have position: static by default. [image](file:///C:/Users/admin/AppData/Local/Packages/oice_16_974fa576_32c1d314_35a6/AC/Temp/msohtmlclip1/01/clip_image001.gif) 🟦 **CSS Box Model & Layout — Q51–100**'),
('CSS', 'Which four areas make up the CSS box model?', 'Content, padding, border, margin', 'Width, height, color, font', 'Header, body, footer, margin', 'Top, bottom, left, right', 'A', 'Medium', 'The box model consists of content, padding, border, and margin.'),
('CSS', 'What is the innermost part of the box model?', 'Margin', 'Border', 'Padding', 'Content', 'D', 'Medium', 'Content is at the center of the box model.'),
('CSS', 'What comes directly outside the content?', 'Margin', 'Padding', 'Border', 'Outline', 'B', 'Medium', 'Padding is the space between content and border.'),
('CSS', 'What comes directly outside padding?', 'Content', 'Margin', 'Border', 'Outline', 'C', 'Medium', 'Border surrounds the padding and content.'),
('CSS', 'What is outside the border?', 'Padding', 'Content', 'Margin', 'Width', 'C', 'Medium', 'Margin creates space outside the border.'),
('CSS', 'Which property changes the box-sizing model?', 'box-sizing', 'box-model', 'size-box', 'model-type', 'A', 'Medium', 'box-sizing determines how width and height are calculated.'),
('CSS', 'What does box-sizing: border-box do?', 'Width excludes padding', 'Width includes content, padding, and border', 'Width includes margin', 'Removes border', 'B', 'Medium', 'With border-box, declared width and height include content, padding, and border.'),
('CSS', 'Which property controls overflowing content?', 'overflow', 'content-overflow', 'flow', 'over-content', 'A', 'Medium', 'overflow controls what happens when content exceeds its box.'),
('CSS', 'Which value clips overflowing content?', 'overflow: hide', 'overflow: clip', 'overflow: remove', 'overflow: cut', 'B', 'Medium', 'clip clips overflowing content without providing scrolling.'),
('CSS', 'Which value adds scrollbars when necessary?', 'overflow: scroll', 'overflow: auto', 'overflow: scrollbar', 'overflow: move', 'B', 'Medium', 'auto allows scrolling when content overflows.'),
('CSS', 'Which property controls horizontal overflow?', 'overflow-x', 'horizontal-overflow', 'x-overflow', 'overflow-horizontal', 'A', 'Medium', 'overflow-x controls overflow in the horizontal direction.'),
('CSS', 'Which property controls vertical overflow?', 'overflow-y', 'vertical-overflow', 'y-overflow', 'overflow-vertical', 'A', 'Medium', 'overflow-y controls vertical overflow.'),
('CSS', 'Which CSS layout system is designed for one-dimensional layouts?', 'Grid', 'Flexbox', 'Table', 'Float', 'B', 'Medium', 'Flexbox is primarily designed for one-dimensional layouts.'),
('CSS', 'Which CSS layout system is designed for two-dimensional layouts?', 'Flexbox', 'Grid', 'Inline', 'Float', 'B', 'Medium', 'CSS Grid handles rows and columns, making it two-dimensional.'),
('CSS', 'Which property turns an element into a flex container?', 'flex: container', 'display: flex', 'layout: flex', 'position: flex', 'B', 'Medium', 'display: flex establishes a flex formatting context.'),
('CSS', 'Which property defines the direction of flex items?', 'flex-direction', 'flex-flow-direction', 'direction-flex', 'item-direction', 'A', 'Medium', 'flex-direction controls whether flex items are arranged in rows or columns.'),
('CSS', 'Which is the default flex-direction?', 'column', 'row', 'row-reverse', 'column-reverse', 'B', 'Medium', 'Flex containers use row as the default main-axis direction.'),
('CSS', 'Which property controls wrapping of flex items?', 'flex-wrap', 'wrap-items', 'item-wrap', 'flex-line', 'A', 'Medium', 'flex-wrap determines whether items can move onto multiple lines.'),
('CSS', 'Which value prevents flex items from wrapping?', 'nowrap', 'no-wrap', 'single', 'fixed', 'A', 'Medium', 'nowrap is the default value of flex-wrap.'),
('CSS', 'Which property aligns flex items along the main axis?', 'align-items', 'justify-content', 'align-content', 'main-align', 'B', 'Medium', 'justify-content distributes flex items along the main axis.'),
('CSS', 'Which property aligns flex items along the cross axis?', 'justify-content', 'align-items', 'cross-content', 'item-position', 'B', 'Medium', 'align-items controls alignment along the cross axis.'),
('CSS', 'Which property controls spacing between flex/grid items?', 'gap', 'space', 'item-spacing', 'element-gap', 'A', 'Medium', 'gap defines spacing between rows and columns in flex and grid layouts.'),
('CSS', 'Which property sets both row and column gaps?', 'gap', 'spacing', 'grid-space', 'flex-gap-only', 'A', 'Medium', 'gap can specify both row and column spacing.'),
('CSS', 'Which declaration creates a grid container?', 'display: grid', 'layout: grid', 'grid: true', 'display: table-grid', 'A', 'Medium', 'display: grid creates a grid formatting context.'),
('CSS', 'Which property defines grid columns?', 'grid-columns', 'grid-template-columns', 'columns-grid', 'grid-column-layout', 'B', 'Medium', 'grid-template-columns defines the grid''s column tracks.'),
('CSS', 'Which property defines grid rows?', 'grid-template-rows', 'grid-rows', 'rows-template', 'grid-row-layout', 'A', 'Medium', 'grid-template-rows defines the grid''s row tracks.'),
('CSS', 'Which unit represents a fraction of available grid space?', '%', 'fr', 'fraction', 'grid', 'B', 'Medium', 'The fr unit represents a fraction of the available grid container space.'),
('CSS', 'What does repeat() do in CSS Grid?', 'Repeats animations', 'Repeats grid track definitions', 'Repeats colors', 'Repeats HTML elements', 'B', 'Medium', 'repeat() simplifies repeated grid track definitions.'),
('CSS', 'Which property controls placement across grid columns?', 'grid-column', 'column-position', 'grid-placement', 'column-grid', 'A', 'Medium', 'grid-column specifies a grid item''s column start/end placement.'),
('CSS', 'Which property controls placement across grid rows?', 'grid-row', 'row-position', 'grid-placement-row', 'row-grid', 'A', 'Medium', 'grid-row controls a grid item''s row placement.'),
('CSS', 'Which property controls the stacking order of positioned elements?', 'stack', 'z-index', 'layer-index', 'position-index', 'B', 'Medium', 'z-index controls stacking order within the relevant stacking contexts.'),
('CSS', 'A higher z-index generally places an element:', 'Further behind', 'Further forward', 'Smaller', 'Lower on the page', 'B', 'Medium', 'Within the same stacking context, a higher stacking level generally appears above a lower one.'),
('CSS', 'Which property creates space between flex/grid items?', 'gap', 'margin-gap', 'space-between', 'item-space', 'A', 'Medium', 'gap creates gutters between items.'),
('CSS', 'Which flex value distributes equal space around items?', 'space-around', 'equal-space', 'around-items', 'space-equal', 'A', 'Medium', 'space-around distributes space around flex items.'),
('CSS', 'Which flex value places equal space between items, with no half-sized gap at the outer edges?', 'space-around', 'space-between', 'space-evenly', 'between-only', 'B', 'Medium', 'space-between places the first and last items at the container edges and distributes remaining space between items.'),
('CSS', 'Which flex value distributes equal space between items and edges?', 'space-evenly', 'space-between', 'space-around', 'equal-gap', 'A', 'Medium', 'space-evenly distributes equal spacing between items and at both edges.'),
('CSS', 'Which property controls an individual flex item''s growth?', 'flex-grow', 'grow-flex', 'item-grow', 'flex-expand', 'A', 'Medium', 'flex-grow determines how much a flex item can grow relative to other items.'),
('CSS', 'Which property controls an individual flex item''s shrinking?', 'flex-shrink', 'shrink-flex', 'item-shrink', 'flex-contract', 'A', 'Medium', 'flex-shrink determines how much an item can shrink.'),
('CSS', 'Which property sets the initial main size of a flex item?', 'flex-basis', 'flex-size', 'basis-size', 'initial-width', 'A', 'Medium', 'flex-basis sets the initial main size before free space is distributed.'),
('CSS', 'Which shorthand combines grow, shrink, and basis?', 'flex', 'flex-box', 'flex-all', 'flex-layout', 'A', 'Medium', 'The flex shorthand combines flex-grow, flex-shrink, and flex-basis.'),
('CSS', 'Which property can change the visual order of flex/grid items?', 'order', 'position', 'sequence', 'item-index', 'A', 'Medium', 'The order property controls the layout order of flex and grid items.'),
('CSS', 'Which property aligns a single flex item independently?', 'align-self', 'self-align', 'item-align', 'individual-align', 'A', 'Medium', 'align-self overrides the container''s align-items value for an individual item.'),
('CSS', 'Which property controls how extra grid content is aligned within the grid container?', 'align-content', 'grid-align', 'content-grid', 'align-grid-items', 'A', 'Medium', 'align-content controls distribution of grid tracks along the block axis when there is extra space.'),
('CSS', 'Which property controls horizontal alignment of grid items in their cells?', 'justify-items', 'grid-horizontal', 'align-items', 'item-horizontal', 'A', 'Medium', 'justify-items controls alignment within grid areas along the inline axis.'),
('CSS', 'Which property controls vertical/block-axis alignment of grid items?', 'align-items', 'justify-items', 'vertical-grid', 'grid-align-y', 'A', 'Medium', 'align-items controls alignment along the block axis in a grid.'),
('CSS', 'Which property controls the position of an absolutely positioned element from the top?', 'top', 'top-position', 'vertical-top', 'position-top', 'A', 'Medium', 'top specifies the inset from the top edge of its containing block.'),
('CSS', 'Which property controls the position from the left?', 'left', 'left-position', 'horizontal-left', 'position-left', 'A', 'Medium', 'left specifies the inset from the left edge.'),
('CSS', 'Which property controls the position from the right?', 'right', 'right-position', 'horizontal-right', 'position-right', 'A', 'Medium', 'right specifies the inset from the right edge.'),
('CSS', 'Which property controls the position from the bottom?', 'bottom', 'bottom-position', 'vertical-bottom', 'position-bottom', 'A', 'Medium', 'bottom specifies the inset from the bottom edge.'),
('CSS', 'Which property can make an element stick during scrolling?', 'position: sticky', 'position: stick', 'sticky: true', 'display: sticky', 'A', 'Medium', 'position: sticky allows an element to behave relatively until a scroll threshold is reached. [image](file:///C:/Users/admin/AppData/Local/Packages/oice_16_974fa576_32c1d314_35a6/AC/Temp/msohtmlclip1/01/clip_image002.gif) 🟦 **CSS Selectors, Pseudo-classes & Pseudo-elements — Q101–150**'),
('CSS', 'Which selector selects all paragraphs inside a div?', 'div \\+ p', 'div p', 'div > p', 'div.p', 'B', 'Medium', 'The descendant selector div p selects paragraphs at any descendant level.'),
('CSS', 'Which selector selects direct child paragraphs of a div?', 'div p', 'div + p', 'div > p', 'div ~ p', 'C', 'Medium', '> selects direct children.'),
('CSS', 'Which selector selects a paragraph immediately following a div?', 'div p', 'div > p', 'div + p', 'div ~ p', 'C', 'Medium', '+ is the adjacent sibling combinator.'),
('CSS', 'Which selector selects all following sibling paragraphs?', 'div \\+ p', 'div ~ p', 'div > p', 'div p', 'B', 'Medium', '~ selects following siblings that match the selector.'),
('CSS', 'Which pseudo-class selects an element when the mouse pointer is over it?', ':mouse', ':hover', ':over', ':pointer', 'B', 'Medium', ':hover applies when a pointing device is over an element.'),
('CSS', 'Which pseudo-class targets a focused element?', ':focus', ':active-focus', ':selected', ':input-focus', 'A', 'Medium', ':focus applies when an element has focus.'),
('CSS', 'Which pseudo-class represents an activated link/button during interaction?', ':click', ':active', ':pressed', ':selected', 'B', 'Medium', ':active represents an element while it is being activated.'),
('CSS', 'Which pseudo-class selects an unvisited link?', ':new', ':unvisited', ':link', ':fresh', 'C', 'Medium', ':link targets links that have not been visited.'),
('CSS', 'Which pseudo-class selects visited links?', ':visited', ':opened', ':history', ':old', 'A', 'Medium', ':visited targets links that have been visited.'),
('CSS', 'Which pseudo-class selects the first child?', ':first', ':first-child', ':child-first', ':first-element', 'B', 'Medium', ':first-child matches an element that is the first child of its parent.'),
('CSS', 'Which pseudo-class selects the last child?', ':last-child', ':child-last', ':last', ':final-child', 'A', 'Medium', ':last-child matches an element that is the last child of its parent.'),
('CSS', 'Which pseudo-class selects every second element?', ':every(2)', ':nth-child(2)', ':second-child', ':child(2)', 'B', 'Medium', ':nth-child(2) selects the second child.'),
('CSS', 'Which selector selects odd children?', ':nth-child(odd)', ':odd-child', ':child-odd', ':nth(odd)', 'A', 'Medium', ':nth-child(odd) selects odd-numbered children.'),
('CSS', 'Which selector selects even children?', ':even', ':nth-child(even)', ':child-even', ':nth(even-child)', 'B', 'Medium', ':nth-child(even) selects even-numbered children.'),
('CSS', 'Which pseudo-class selects elements that are the only child?', ':single-child', ':only-child', ':one-child', ':unique-child', 'B', 'Medium', ':only-child matches an element with no siblings.'),
('CSS', 'Which pseudo-class selects empty elements?', ':empty', ':blank', ':none', ':empty-element', 'A', 'Medium', ':empty matches elements with no children.'),
('CSS', 'Which pseudo-class selects enabled form controls?', ':active', ':enabled', ':available', ':usable', 'B', 'Medium', ':enabled matches enabled form controls.'),
('CSS', 'Which pseudo-class selects disabled form controls?', ':disabled', ':inactive', ':blocked', ':off', 'A', 'Medium', ':disabled matches disabled form controls.'),
('CSS', 'Which pseudo-class selects checked checkboxes/radio buttons?', ':selected', ':checked', ':chosen', ':marked', 'B', 'Medium', ':checked matches selected checkbox and radio inputs.'),
('CSS', 'Which pseudo-class selects required form controls?', ':required', ':mandatory', ':needed', ':must', 'A', 'Medium', ':required matches controls with the required attribute.'),
('CSS', 'Which pseudo-class selects valid form controls?', ':correct', ':valid', ':accepted', ':verified', 'B', 'Medium', ':valid matches elements whose form value satisfies applicable constraints.'),
('CSS', 'Which pseudo-class selects invalid form controls?', ':wrong', ':invalid', ':error', ':incorrect', 'B', 'Medium', ':invalid matches controls whose value fails applicable constraints.'),
('CSS', 'Which pseudo-element selects the first line of text?', '::first-line', '::line-first', ':first-line', '::first', 'A', 'Medium', '::first-line styles the first formatted line of a block.'),
('CSS', 'Which pseudo-element selects the first letter?', '::first-character', '::first-letter', '::letter-first', ':first-letter', 'B', 'Medium', '::first-letter styles the first letter of a block.'),
('CSS', 'Which pseudo-elements are commonly used to insert generated content?', '::before and ::after', '::start and ::end', '::top and ::bottom', '::insert and ::append', 'A', 'Medium', '::before and ::after can generate content through the content property.'),
('CSS', 'Which property is required to generate content with ::before?', 'text', 'content', 'insert', 'value', 'B', 'Medium', 'Generated pseudo-element content is controlled with the content property.'),
('CSS', 'Which selector targets an attribute?', 'element{attribute}', '[attribute]', '#attribute', '.attribute', 'B', 'Medium', 'Square brackets create attribute selectors.'),
('CSS', 'Which selector matches elements with type="text"?', '[type=text]', '.type=text', '#type=text', 'type("text")', 'A', 'Medium', '[type="text"] selects elements whose type attribute equals text.'),
('CSS', 'Which selector matches elements whose class contains a specific word?', '[class~="box"]', '[class="box"]', '[class*="box"]', '[class+="box"]', 'A', 'Medium', '~= matches a whitespace-separated word in an attribute value.'),
('CSS', 'Which selector matches an attribute containing a substring?', '[attr~="x"]', '[attr*="x"]', '[attr^="x"]', '[attr$="x"]', 'B', 'Medium', '*= matches when the attribute value contains the specified substring.'),
('CSS', 'Which selector matches an attribute beginning with a value?', '[attr^="x"]', '[attr*="x"]', '[attr$="x"]', '[attr~="x"]', 'A', 'Medium', '^= matches an attribute value beginning with the specified string.'),
('CSS', 'Which selector matches an attribute ending with a value?', '[attr^="x"]', '[attr$="x"]', '[attr*="x"]', '[attr~="x"] $= matches an attribute value ending with the specified string.', 'B', 'Medium', '=$ matches an attribute value ending with the specified string.'),
('CSS', 'Which pseudo-class selects the root element?', ':html', ':root', ':document', ':page', 'B', 'Medium', ':root represents the document''s root element.'),
('CSS', 'Which pseudo-class selects elements that do not match a selector?', ':not()', ':exclude()', ':without()', ':except()', 'A', 'Medium', ':not() represents elements that do not match its argument selector.'),
('CSS', 'Which pseudo-class can select elements matching a list of selectors?', ':is()', ':match-all()', ':select()', ':same()', 'A', 'Medium', ':is() matches an element against one or more selectors.'),
('CSS', 'Which pseudo-class allows you to group multiple selectors while using the specificity of the most specific selector?', ':where()', ':is()', ':first()', ':match()', 'B', 'Medium', ':is() is a forgiving selector-list pseudo-class; it selects elements matching any selector in its list and does not inherently mean "first element."'),
('CSS', 'Which pseudo-class has zero specificity for its arguments?', ':is()', ':where()', ':not()', ':has()', 'B', 'Medium', ':where() and its arguments have zero specificity.'),
('CSS', 'Which pseudo-class selects an element based on whether it has a matching descendant?', ':has()', ':contains()', ':child()', ':descendant()', 'A', 'Medium', ':has() is a relational pseudo-class that can select an element based on related elements.'),
('CSS', 'Which selector selects a paragraph that has a class note?', 'p.note', 'p#note', 'p note', 'p.note()', 'A', 'Medium', 'p.note selects \\<p> elements having the note class.'),
('CSS', 'Which selector selects an element having both classes box and active?', '.box .active', '.box.active', '.box + .active', '.box > .active .box.active matches one element containing both classes.', 'B', 'Medium', '.box.active matches one element containing both classes.'),
('CSS', 'Which selector selects all paragraphs and divs?', 'p div', 'p, div', 'p + div', 'p > div', 'B', 'Medium', 'A comma creates a selector list.'),
('CSS', 'Which selector targets an element with ID header?', '.header', 'header', '#header', '*header', 'C', 'Medium', '#header targets the element whose ID is header.'),
('CSS', 'Which selector has lower specificity?', 'ID', 'Class', 'Element', 'Inline style', 'C', 'Medium', 'Element selectors have lower specificity than class and ID selectors.'),
('CSS', 'Which selector generally has the highest specificity?', 'Universal', 'Element', 'Class', 'ID', 'D', 'Medium', 'ID selectors have greater specificity than class and element selectors.'),
('CSS', 'Which selector matches every \\<li> that is the first child?', 'li:first-child', 'li:first', 'li:child-first', 'li:first-element', 'A', 'Medium', ':first-child checks whether the element is the first child of its parent.'),
('CSS', 'Which pseudo-class represents the state of an element while it has keyboard focus?', ':keyboard', ':focus', ':active-key', ':tab', 'B', 'Medium', ':focus applies when an element has focus.'),
('CSS', 'Which pseudo-class indicates keyboard focus that is typically visible to the user?', ':focus-visible', ':visible-focus', ':keyboard-focus', ':focus-show', 'A', 'Medium', ':focus-visible is intended for focus styles when the browser determines they should be visibly indicated.'),
('CSS', 'Which pseudo-class selects the first element of a given type among siblings?', ':first-child', ':first-of-type', ':type-first', ':first-element-type', 'B', 'Medium', ':first-of-type selects the first sibling of its element type.'),
('CSS', 'Which pseudo-class selects the last element of a given type?', ':last-of-type', ':last-type', ':type-last', ':last-element-type', 'A', 'Medium', ':last-of-type selects the last sibling of its element type.'),
('CSS', 'Which selector targets the first letter of every paragraph?', 'p::first-letter', 'p:first', 'p::letter-first', 'p:first-letter()', 'A', 'Medium', 'p::first-letter targets the first letter of each paragraph. 🟦 **CSS Advanced, Responsive Design, Animation & Modern CSS — Q151–200**'),
('CSS', 'Which unit is relative to the root element''s font size?', 'em', 'rem', '%', 'vh', 'B', 'Hard', 'rem is relative to the root element''s font size.'),
('CSS', 'Which unit is relative to the font size of the current element?', 'rem', 'em', 'vh', 'vw', 'B', 'Hard', 'em is generally relative to the font size of the element or its parent depending on the property.'),
('CSS', 'Which unit represents 1% of viewport width?', 'vh', 'vw', 'vmin', 'w', 'B', 'Hard', '1vw equals 1% of the viewport width.'),
('CSS', 'Which unit represents 1% of viewport height?', 'vh', 'vw', 'vmax', 'h', 'A', 'Hard', '1vh equals 1% of the viewport height.'),
('CSS', 'Which unit is relative to the smaller viewport dimension?', 'vmax', 'vmin', 'vm', 'small-vh', 'B', 'Hard', 'vmin represents 1% of the smaller viewport dimension.'),
('CSS', 'Which unit is relative to the larger viewport dimension?', 'vmax', 'vmin', 'vwmax', 'large-vh', 'A', 'Hard', 'vmax represents 1% of the larger viewport dimension.'),
('CSS', 'Which CSS rule is used for responsive media queries?', '@responsive', '@media', '@screen', '@device', 'B', 'Hard', '@media applies CSS conditionally based on media features such as viewport width.'),
('CSS', 'Which media feature commonly checks viewport width?', 'screen-width', 'width', 'viewport-width', 'device-width-only', 'B', 'Hard', 'Within a media query, width checks the viewport''s width.'),
('CSS', 'Which CSS function performs calculations?', 'calc()', 'calculate()', 'math()', 'compute()', 'A', 'Hard', 'calc() allows arithmetic calculations in CSS values.'),
('CSS', 'Which CSS function sets a minimum preferred and maximum value?', 'range()', 'clamp()', 'limit()', 'minmax-value()', 'B', 'Hard', 'clamp(min, preferred, max) constrains a value between a minimum and maximum.'),
('CSS', 'Which function returns the smallest value?', 'small()', 'min()', 'lowest()', 'minimum()', 'B', 'Hard', 'min() returns the smallest value from its arguments.'),
('CSS', 'Which function returns the largest value?', 'max()', 'large()', 'highest()', 'maximum()', 'A', 'Hard', 'max() returns the largest value from its arguments.'),
('CSS', 'Which property creates smooth changes between CSS values?', 'transition', 'change', 'smooth', 'animate-transition', 'A', 'Hard', 'CSS transitions interpolate changes in property values over time.'),
('CSS', 'Which property specifies transition duration?', 'transition-time', 'transition-duration', 'duration', 'change-duration', 'B', 'Hard', 'transition-duration specifies how long a transition takes.'),
('CSS', 'Which property specifies which properties should transition?', 'transition-property', 'property-transition', 'transition-values', 'animate-property', 'A', 'Hard', 'transition-property specifies the CSS properties affected by transitions.'),
('CSS', 'Which property controls the speed curve of a transition?', 'transition-timing-function', 'transition-speed', 'timing', 'animation-curve', 'A', 'Hard', 'transition-timing-function controls the interpolation curve.'),
('CSS', 'Which property delays the start of a transition?', 'transition-delay', 'delay-transition', 'transition-start', 'start-delay', 'A', 'Hard', 'transition-delay specifies how long to wait before the transition starts.'),
('CSS', 'Which CSS feature defines animation stages?', '@animation', '@keyframes', '@frames', '@motion', 'B', 'Hard', '@keyframes defines the intermediate stages of a CSS animation.'),
('CSS', 'Which property specifies the animation name?', 'animation-name', 'keyframe-name', 'animation-id', 'motion-name', 'A', 'Hard', 'animation-name specifies which @keyframes animation to use.'),
('CSS', 'Which property controls animation duration?', 'animation-time', 'animation-duration', 'duration-animation', 'animation-length', 'B', 'Hard', 'animation-duration specifies how long one animation cycle takes.'),
('CSS', 'Which property controls the number of animation repetitions?', 'animation-count', 'animation-iteration-count', 'repeat-animation', 'animation-repeat-count', 'B', 'Hard', 'animation-iteration-count controls how many times the animation runs.'),
('CSS', 'Which value makes an animation repeat indefinitely?', 'repeat', 'forever', 'infinite', 'always', 'C', 'Hard', 'animation-iteration-count: infinite repeats the animation indefinitely.'),
('CSS', 'Which property controls the animation direction?', 'animation-direction', 'animation-flow', 'direction-animation', 'motion-direction', 'A', 'Hard', 'animation-direction controls whether animation runs forward, reverse, or alternates.'),
('CSS', 'Which property controls whether an animation is running or paused?', 'animation-state', 'animation-play-state', 'play-animation', 'animation-control', 'B', 'Hard', 'animation-play-state accepts values such as running and paused.'),
('CSS', 'Which property controls what styles apply before/after an animation?', 'animation-fill-mode', 'animation-style', 'fill-animation', 'animation-state-style', 'A', 'Hard', 'animation-fill-mode controls styles applied before and after an animation.'),
('CSS', 'Which CSS property rotates, scales, or moves an element?', 'transform', 'change', 'modify', 'object-transformer', 'A', 'Hard', 'transform applies geometric transformations.'),
('CSS', 'Which transform function rotates an element?', 'turn()', 'rotate()', 'spin()', 'rotation()', 'B', 'Hard', 'rotate() rotates an element around its transform origin.'),
('CSS', 'Which transform function changes the size?', 'resize()', 'scale()', 'size()', 'zoom()', 'B', 'Hard', 'scale() changes an element''s size along one or more axes.'),
('CSS', 'Which transform function moves an element?', 'move()', 'translate()', 'position()', 'shift()', 'B', 'Hard', 'translate() moves an element without affecting normal document flow.'),
('CSS', 'Which property controls the point around which transforms occur?', 'transform-point', 'transform-origin', 'origin-transform', 'rotation-origin-only', 'B', 'Hard', 'transform-origin defines the origin for transformations.'),
('CSS', 'Which property controls how an element''s content is clipped to its border box?', 'clip-content', 'overflow', 'content-clip', 'box-clip', 'B', 'Hard', 'overflow controls whether overflowing content is visible, clipped, or scrollable.'),
('CSS', 'Which CSS function can create a linear color gradient?', 'linear-gradient()', 'line-gradient()', 'gradient-linear()', 'color-line()', 'A', 'Hard', 'linear-gradient() creates a gradient along a straight line.'),
('CSS', 'Which function creates a radial gradient?', 'circle-gradient()', 'radial-gradient()', 'round-gradient()', 'radial-color()', 'B', 'Hard', 'radial-gradient() creates a gradient radiating from a point.'),
('CSS', 'Which property controls an element''s background image?', 'background-image', 'image-background', 'bg-image', 'background-src', 'A', 'Hard', 'background-image specifies one or more background images.'),
('CSS', 'Which property controls how a background image is sized?', 'background-size', 'image-size', 'background-scale', 'bg-dimensions', 'A', 'Hard', 'background-size controls the rendered size of background images.'),
('CSS', 'Which value makes a background image cover the entire container?', 'contain', 'cover', 'full', 'stretch', 'B', 'Hard', 'background-size: cover scales the image to cover the container, potentially cropping it.'),
('CSS', 'Which value makes a background image fully visible within its container?', 'cover', 'contain', 'fit', 'complete', 'B', 'Hard', 'contain scales the image so the entire image fits inside the container.'),
('CSS', 'Which property controls where a background image starts?', 'background-position', 'background-location', 'image-position', 'background-place', 'A', 'Hard', 'background-position controls the position of a background image.'),
('CSS', 'Which property controls whether a background image repeats?', 'background-repeat', 'repeat-background', 'image-repeat', 'bg-loop', 'A', 'Hard', 'background-repeat determines how background images are tiled.'),
('CSS', 'Which property controls whether an image fits inside an \\<img> element''s box?', 'object-fit', 'image-fit', 'fit-image', 'object-size', 'A', 'Hard', 'object-fit controls how replaced content such as images fits within its box.'),
('CSS', 'Which object-fit value preserves the image''s aspect ratio while filling the box?', 'fill', 'cover', 'contain', 'stretch', 'B', 'Hard', 'cover fills the box while preserving aspect ratio, cropping when necessary.'),
('CSS', 'Which CSS variable syntax is correct?', '$main-color', '\\--main-color', '@main-color', 'var-main-color', 'B', 'Hard', 'Custom properties are declared using names beginning with --.'),
('CSS', 'Which function reads a CSS custom property?', 'value()', 'get()', 'var()', 'custom()', 'C', 'Hard', 'var(--property-name) retrieves the value of a custom property.'),
('CSS', 'Where are global CSS variables commonly declared?', ':root', ':global', 'body-root', 'html-global', 'A', 'Hard', ':root is commonly used to declare custom properties available throughout the document.'),
('CSS', 'Which at-rule can register a CSS custom property and define its syntax?', '@variable', '@property', '@custom', '@value', 'B', 'Hard', '@property can register a custom property and define its syntax, inheritance, and initial value.'),
('CSS', 'Which CSS property changes the mouse pointer appearance?', 'mouse', 'pointer', 'cursor', 'mouse-pointer', 'C', 'Hard', 'cursor specifies the type of cursor shown when pointing at an element.'),
('CSS', 'Which cursor value commonly displays a hand/pointer?', 'hand', 'pointer', 'click', 'finger', 'B', 'Hard', 'cursor: pointer commonly displays a pointer cursor.'),
('CSS', 'Which property controls whether an element can receive pointer events?', 'pointer-events', 'mouse-events', 'click-events', 'interaction', 'A', 'Hard', 'pointer-events controls how an element participates in pointer hit-testing.'),
('CSS', 'Which CSS flag can give a declaration higher priority than normal declarations in the cascade?', '!important', '!priority', '!force', '!override', 'A', 'Hard', '!important increases the priority of a declaration, although it should be used carefully.'),
('CSS', 'Which statement best describes CSS?', 'CSS is primarily used to structure databases', 'CSS is primarily used to style and lay out web documents', 'CSS is a server-side programming language', 'CSS is a replacement for HTML', 'B', 'Hard', 'CSS controls the visual presentation and layout of HTML/XML-based documents.');

-- Verification
SELECT COUNT(*) AS css_questions
FROM questions
WHERE skill = 'CSS';

SELECT COUNT(DISTINCT question) AS unique_css_questions
FROM questions
WHERE skill = 'CSS';

SELECT skill, COUNT(*) AS question_count
FROM questions
GROUP BY skill
ORDER BY skill;