USE ai_interviewer;

-- HTML 200 MCQs
-- Source: Pasted text.txt
-- Difficulty mapping (source did not specify difficulty): Q1-50 = Easy, Q51-150 = Medium, Q151-200 = Hard.
-- Existing 60 HTML questions were deleted before this insert.

INSERT INTO questions
(skill, question, option_a, option_b, option_c, option_d, correct_answer, difficulty, explanation)
VALUES
('HTML', 'What does HTML stand for?', 'Hyper Text Markup Language', 'High Text Machine Language', 'Hyperlink Text Management Language', 'Home Tool Markup Language', 'A', 'Easy', 'HTML stands for Hyper Text Markup Language and is used to structure web pages.'),
('HTML', 'Which tag is used to define the root of an HTML document?', '<body>', '<html>', '<head>', '<root>', 'B', 'Easy', 'The <html> element is the root element of an HTML document.'),
('HTML', 'Which tag contains the visible content of a webpage?', '<head>', '<title>', '<body>', '<html>', 'C', 'Easy', 'Content displayed in the browser is generally placed inside <body>.'),
('HTML', 'Which tag defines the title shown in the browser tab?', '<header>', '<title>', '<heading>', '<caption>', 'B', 'Easy', 'The <title> element specifies the document title shown in the browser tab.'),
('HTML', 'Which tag is used for the largest heading?', '<h6>', '<head>', '<h1>', '<heading>', 'C', 'Easy', '<h1> represents the highest-level heading.'),
('HTML', 'Which tag defines a paragraph?', '<para>', '<p>', '<paragraph>', '<text>', 'B', 'Easy', 'The <p> tag defines a paragraph.'),
('HTML', 'Which tag creates a line break?', '<break>', '<lb>', '<br>', '<newline>', 'C', 'Easy', '<br> inserts a line break.'),
('HTML', 'Which tag creates a horizontal thematic break?', '<line>', '<hr>', '<break>', '<horizontal>', 'B', 'Easy', '<hr> represents a thematic break, commonly displayed as a horizontal line.'),
('HTML', 'Which HTML element is used to create a hyperlink?', '<link>', '<a>', '<href>', '<url>', 'B', 'Easy', 'The <a> element creates hyperlinks.'),
('HTML', 'Which attribute specifies the destination of a hyperlink?', 'src', 'link', 'href', 'url', 'C', 'Easy', 'The href attribute specifies the URL where the link points.'),
('HTML', 'Which tag is used to display an image?', '<picture>', '<img>', '<image>', '<src> ✅ Correct Answer B:', 'B', 'Easy', 'The <img> element embeds an image in an HTML page.'),
('HTML', 'Which attribute specifies the image URL?', 'href', 'link', 'src', 'url', 'C', 'Easy', 'The src attribute specifies the source of the image.'),
('HTML', 'Which attribute provides alternative text for an image?', 'title', 'alt', 'text', 'description', 'B', 'Easy', 'alt provides alternative text when an image cannot be displayed and helps accessibility.'),
('HTML', 'Which tag creates an unordered list?', '<ol>', '<list>', '<ul>', '<li>', 'C', 'Easy', '<ul> creates an unordered/bulleted list.'),
('HTML', 'Which tag creates an ordered list?', '<ol>', '<ul>', '<order>', '<li>', 'A', 'Easy', '<ol> creates a numbered or ordered list.'),
('HTML', 'Which tag represents an individual list item?', '<item>', '<li>', '<list>', '<i>', 'B', 'Easy', '<li> represents a list item inside <ul> or <ol>.'),
('HTML', 'Which tag is used to create a table?', '<table>', '<tab>', '<tbl>', '<grid>', 'A', 'Easy', 'The <table> element defines an HTML table.'),
('HTML', 'Which tag defines a table row?', '<td>', '<tr>', '<row>', '<th>', 'B', 'Easy', '<tr> defines a table row.'),
('HTML', 'Which tag defines a normal table cell?', '<cell>', '<tc>', '<td>', '<tr>', 'C', 'Easy', '<td> defines a standard table data cell.'),
('HTML', 'Which tag defines a table header cell?', '<thead>', '<header>', '<th>', '<td>', 'C', 'Easy', '<th> represents a header cell in a table.'),
('HTML', 'Which tag defines the header section of a table?', '<header>', '<thead>', '<th>', '<tablehead>', 'B', 'Easy', '<thead> groups the header rows of a table.'),
('HTML', 'Which tag defines the body section of a table?', '<tbody>', '<body>', '<tablebody>', '<tb>', 'A', 'Easy', '<tbody> groups the main data rows of a table.'),
('HTML', 'Which tag defines the footer section of a table?', '<footer>', '<tfoot>', '<tablefooter>', '<tf>', 'B', 'Easy', '<tfoot> groups footer rows in a table.'),
('HTML', 'Which attribute merges table columns?', 'rowspan', 'colspan', 'mergecol', 'span-column', 'B', 'Easy', 'colspan specifies how many columns a cell should span.'),
('HTML', 'Which attribute merges table rows?', 'rowspan', 'colspan', 'mergerow', 'spanrow', 'A', 'Easy', 'rowspan specifies how many rows a cell should span.'),
('HTML', 'Which tag is used to create a form?', '<input>', '<form>', '<forms>', '<fieldset>', 'B', 'Easy', '<form> creates a section for collecting user input.'),
('HTML', 'Which HTML element is commonly used for single-line text input?', '<text>', '<input>', '<textarea>', '<textbox>', 'B', 'Easy', '<input type="text"> creates a single-line text field.'),
('HTML', 'Which input type is used for passwords?', 'type="pass"', 'type="password"', 'type="secure"', 'type="hidden-password"', 'B', 'Easy', 'password hides the characters entered by the user.'),
('HTML', 'Which input type creates a checkbox?', 'type="check"', 'type="checkbox"', 'type="tick"', 'type="select"', 'B', 'Easy', '<input type="checkbox"> creates a checkbox.'),
('HTML', 'Which input type creates a radio button?', 'type="radio"', 'type="option"', 'type="button-radio"', 'type="select"', 'A', 'Easy', 'radio creates a radio button.'),
('HTML', 'Which tag creates a multi-line text input?', '<input>', '<textarea>', '<text>', '<multiline>', 'B', 'Easy', '<textarea> allows users to enter multiple lines of text.'),
('HTML', 'Which tag creates a dropdown list?', '<dropdown>', '<select>', '<list>', '<optionlist>', 'B', 'Easy', '<select> creates a dropdown/select control.'),
('HTML', 'Which tag defines an option inside a dropdown?', '<choice>', '<item>', '<option>', '<select-item>', 'C', 'Easy', '<option> defines an individual choice inside <select>.'),
('HTML', 'Which attribute makes an input field mandatory?', 'required', 'mandatory', 'needed', 'must', 'A', 'Easy', 'The Boolean required attribute prevents form submission when the field is empty.'),
('HTML', 'Which attribute displays hint text inside an input field?', 'hint', 'placeholder', 'help', 'tooltip', 'B', 'Easy', 'placeholder displays temporary hint text inside an input.'),
('HTML', 'Which attribute gives an input its submitted name?', 'id', 'name', 'key', 'input-name', 'B', 'Easy', 'The name attribute identifies form data when it is submitted.'),
('HTML', 'Which attribute uniquely identifies an HTML element?', 'class', 'id', 'name', 'key', 'B', 'Easy', 'An id should uniquely identify an element within a document.'),
('HTML', 'Which attribute is used to assign one or more CSS classes?', 'style', 'class', 'css', 'classname', 'B', 'Easy', 'The class attribute assigns CSS classes to elements.'),
('HTML', 'Which attribute contains inline CSS?', 'css', 'style', 'design', 'format', 'B', 'Easy', 'The style attribute contains inline CSS declarations.'),
('HTML', 'Which tag is used to define metadata?', '<meta>', '<data>', '<metadata>', '<info>', 'A', 'Easy', '<meta> provides metadata about the HTML document.'),
('HTML', 'Which declaration specifies HTML5?', '<!HTML5>', '<!DOCTYPE HTML>', '<DOCTYPE html5>', '<!HTML VERSION="5">', 'B', 'Easy', '<!DOCTYPE html> tells the browser to use the HTML standard mode.'),
('HTML', 'Is <!DOCTYPE html> an HTML element?', 'Yes', 'No', 'Only in HTML5', 'Only in XML', 'B', 'Easy', 'DOCTYPE is a declaration, not an HTML element.'),
('HTML', 'Which tag contains metadata and links to resources?', '<body>', '<head>', '<main>', '<section>', 'B', 'Easy', 'The <head> contains metadata, title, stylesheets, scripts, and related information.'),
('HTML', 'Which tag is used to connect an external CSS file?', '<css>', '<style>', '<link>', '<stylesheet>', 'C', 'Easy', '<link> is commonly used to reference an external stylesheet.'),
('HTML', 'Which tag is used for internal CSS?', '<css>', '<style>', '<design>', '<stylesheet>', 'B', 'Easy', 'CSS written inside <style> is internal CSS.'),
('HTML', 'Which tag is used to add JavaScript to HTML?', '<javascript>', '<js>', '<script>', '<code>', 'C', 'Easy', 'The <script> element embeds or references JavaScript.'),
('HTML', 'Which HTML element represents emphasized text?', '<strong>', '<em>', '<italic>', '<emphasis>', 'B', 'Easy', '<em> represents stress emphasis.'),
('HTML', 'Which element represents strong importance?', '<bold>', '<important>', '<strong>', '<bolder>', 'C', 'Easy', '<strong> represents text with strong importance.'),
('HTML', 'Which tag usually renders text in bold without adding semantic importance?', '<b>', '<strong>', '<bold>', '<heavy>', 'A', 'Easy', '<b> draws attention to text without implying strong importance.'),
('HTML', 'Which tag usually renders text in italic without specifically representing emphasis?', '<i>', '<italic>', '<emphasis>', '<slant>', 'A', 'Easy', '<i> represents text offset from the normal prose, often displayed in italics. Questions 51–100: HTML Elements, Attributes & Forms'),
('HTML', 'Which element is used for a quotation from another source?', '<quote>', '<blockquote>', '<qoute>', '<citation>', 'B', 'Medium', '<blockquote> represents an extended quotation.'),
('HTML', 'Which element represents a short inline quotation?', '<quote>', '<q>', '<shortquote>', '<inlinequote>', 'B', 'Medium', '<q> is used for short inline quotations.'),
('HTML', 'Which element represents a definition term?', '<dt>', '<dd>', '<def>', '<term>', 'A', 'Medium', '<dt> defines a term in a description list.'),
('HTML', 'Which element represents the description of a term?', '<description>', '<dd>', '<dt>', '<desc>', 'B', 'Medium', '<dd> contains the description/details of a term.'),
('HTML', 'Which element creates a description list?', '<dl>', '<list>', '<description>', '<dlist>', 'A', 'Medium', '<dl> creates a description list.'),
('HTML', 'Which element represents computer code?', '<program>', '<code>', '<coding>', '<computer>', 'B', 'Medium', '<code> represents a fragment of computer code.'),
('HTML', 'Which element preserves whitespace and line breaks?', '<space>', '<pre>', '<preserve>', '<text>', 'B', 'Medium', '<pre> displays preformatted text while preserving whitespace.'),
('HTML', 'Which element is used for superscript text?', '<super>', '<sup>', '<top>', '<up>', 'B', 'Medium', '<sup> displays text as superscript.'),
('HTML', 'Which element is used for subscript text?', '<sub>', '<bottom>', '<down>', '<subscript-text>', 'A', 'Medium', '<sub> displays text as subscript.'),
('HTML', 'Which tag is used to highlight text?', '<highlight>', '<mark>', '<yellow>', '<hl>', 'B', 'Medium', '<mark> represents text highlighted for relevance.'),
('HTML', 'Which element represents deleted text?', '<remove>', '<delete>', '<del>', '<strikeout>', 'C', 'Medium', '<del> represents text that has been deleted from a document.'),
('HTML', 'Which element represents inserted text?', '<insert>', '<ins>', '<add>', '<new>', 'B', 'Medium', '<ins> represents text that has been inserted.'),
('HTML', 'Which attribute opens a link in a new browsing context?', 'new', 'target="_blank"', 'open="new"', 'window="new"', 'B', 'Medium', 'target="_blank" requests a new browsing context, commonly a new tab.'),
('HTML', 'Which attribute provides a tooltip-like advisory text?', 'tooltip', 'title', 'hint', 'help', 'B', 'Medium', 'The title attribute can provide advisory information, often shown as a tooltip.'),
('HTML', 'Which attribute makes a checkbox selected by default?', 'selected', 'checked', 'active', 'default', 'B', 'Medium', 'checked specifies that a checkbox or radio button is selected initially.'),
('HTML', 'Which attribute makes an option selected by default?', 'checked', 'selected', 'active', 'chosen', 'B', 'Medium', 'selected marks an <option> as initially selected.'),
('HTML', 'Which attribute prevents the user from editing an input?', 'readonly', 'disabled', 'locked', 'fixed', 'A', 'Medium', 'readonly prevents editing while generally allowing the value to remain focusable and submitted.'),
('HTML', 'Which attribute disables an input?', 'inactive', 'disabled', 'readonly', 'blocked', 'B', 'Medium', 'disabled prevents user interaction with the form control.'),
('HTML', 'Which input type is used for email addresses?', 'type="mail"', 'type="email"', 'type="address"', 'type="e-mail"', 'B', 'Medium', 'type="email" is designed for email address input and provides browser validation.'),
('HTML', 'Which input type is used for numeric values?', 'type="number"', 'type="numeric"', 'type="integer"', 'type="digit"', 'A', 'Medium', '<input type="number"> is intended for numeric input.'),
('HTML', 'Which input type allows selecting a date?', 'type="calendar"', 'type="date"', 'type="day"', 'type="datetime"', 'B', 'Medium', 'type="date" provides a date input control.'),
('HTML', 'Which input type allows selecting a color?', 'type="paint"', 'type="color"', 'type="colour-picker"', 'type="palette"', 'B', 'Medium', 'type="color" provides a color picker.'),
('HTML', 'Which input type allows file selection?', 'type="upload"', 'type="file"', 'type="document"', 'type="attachment"', 'B', 'Medium', 'type="file" lets the user select files from their device.'),
('HTML', 'Which input type creates a submit button?', 'type="send"', 'type="submit"', 'type="button-submit"', 'type="form"', 'B', 'Medium', 'type="submit" creates a button that submits the form.'),
('HTML', 'Which input type creates a reset button?', 'type="clear"', 'type="reset"', 'type="restart"', 'type="refresh"', 'B', 'Medium', 'type="reset" resets form controls to their initial values.'),
('HTML', 'Which tag associates a text label with a form control?', '<caption>', '<label>', '<name>', '<formlabel>', 'B', 'Medium', '<label> provides a caption for a form control and improves usability/accessibility.'),
('HTML', 'Which attribute connects a <label> to an input''s id?', 'for', 'id', 'target', 'control', 'A', 'Medium', 'The label''s for value should match the input''s id.'),
('HTML', 'Which form attribute specifies where submitted data is sent?', 'target', 'action', 'destination', 'url', 'B', 'Medium', 'action specifies the URL that processes the submitted form data.'),
('HTML', 'Which form attribute specifies the HTTP method?', 'type', 'method', 'request', 'http', 'B', 'Medium', 'method specifies how form data is submitted, such as GET or POST.'),
('HTML', 'Which form method appends form data to the URL?', 'POST', 'GET', 'PUT', 'SEND', 'B', 'Medium', 'GET places form data in the URL query string.'),
('HTML', 'Which form method generally sends data in the request body?', 'GET', 'POST', 'LINK', 'QUERY', 'B', 'Medium', 'POST sends submitted form data in the HTTP request body.'),
('HTML', 'Which attribute prevents browser validation when submitting a form?', 'novalidate', 'disablevalidation', 'validate="false"', 'no-check', 'A', 'Medium', 'novalidate disables the browser''s built-in form validation for that form.'),
('HTML', 'Which element groups related form controls?', '<group>', '<fieldset>', '<formgroup>', '<controls>', 'B', 'Medium', '<fieldset> groups related controls.'),
('HTML', 'Which element provides a caption for a <fieldset>?', '<caption>', '<legend>', '<title>', '<label>', 'B', 'Medium', '<legend> provides a caption for a <fieldset>.'),
('HTML', 'Which input type creates a hidden field?', 'type="secret"', 'type="hidden"', 'type="invisible"', 'type="none"', 'B', 'Medium', 'Hidden inputs are not displayed to users but can carry form data.'),
('HTML', 'Which input type creates a search field?', 'type="find"', 'type="search"', 'type="query"', 'type="lookup"', 'B', 'Medium', 'type="search" is intended for search terms.'),
('HTML', 'Which input type is used for telephone numbers?', 'type="telephone"', 'type="phone"', 'type="tel"', 'type="mobile"', 'C', 'Medium', 'type="tel" is intended for telephone number input.'),
('HTML', 'Which input type is used to enter a URL?', 'type="link"', 'type="url"', 'type="website"', 'type="web"', 'B', 'Medium', 'type="url" is designed for URL input.'),
('HTML', 'Which input attribute defines the minimum allowed value for number/date inputs?', 'low', 'min', 'minimum', 'start', 'B', 'Medium', 'min specifies the minimum permitted value.'),
('HTML', 'Which attribute defines the maximum allowed value?', 'max', 'maximum', 'high', 'limit', 'A', 'Medium', 'max specifies the maximum permitted value.'),
('HTML', 'Which attribute specifies the number of characters allowed in a text input?', 'length', 'maxlength', 'characters', 'maxchars', 'B', 'Medium', 'maxlength limits the number of characters that can be entered.'),
('HTML', 'Which attribute specifies the minimum number of characters?', 'minlength', 'minimum', 'minchars', 'length-min', 'A', 'Medium', 'minlength specifies the minimum number of characters required.'),
('HTML', 'Which attribute specifies a regular expression for input validation?', 'regex', 'pattern', 'validate', 'expression', 'B', 'Medium', 'pattern specifies a regular expression that the input''s value must match.'),
('HTML', 'Which attribute controls the increment for number/range inputs?', 'step', 'increment', 'interval', 'jump', 'A', 'Medium', 'step specifies valid increments for certain input types.'),
('HTML', 'Which element creates a progress indicator?', '<loading>', '<progress>', '<status>', '<bar>', 'B', 'Medium', '<progress> represents the completion progress of a task.'),
('HTML', 'Which element represents a scalar measurement within a known range?', '<measure>', '<meter>', '<range>', '<scale>', 'B', 'Medium', '<meter> represents a scalar measurement within a known range.'),
('HTML', 'Which element creates a button?', '<button>', '<btn>', '<click>', '<control>', 'A', 'Medium', '<button> represents a clickable button.'),
('HTML', 'What is the default type of a <button> inside a form?', 'submit', 'reset', 'button', 'click', 'A', 'Medium', 'A <button> inside a form defaults to type="submit" unless another type is specified.'),
('HTML', 'Which element is used to embed another webpage?', '<frame>', '<iframe>', '<embedpage>', '<webframe>', 'B', 'Medium', '<iframe> embeds another HTML page or browsing context.'),
('HTML', 'Which attribute specifies the URL loaded into an iframe?', 'href', 'src', 'url', 'link', 'B', 'Medium', 'The src attribute specifies the resource displayed inside the iframe. Questions 101–150: HTML5 & Semantic HTML'),
('HTML', 'Which element represents the main content of a document?', '<content>', '<main>', '<primary>', '<body-content>', 'B', 'Medium', '<main> represents the dominant content of the document.'),
('HTML', 'Which element represents introductory content?', '<intro>', '<header>', '<top>', '<heading>', 'B', 'Medium', '<header> represents introductory content or navigational aids.'),
('HTML', 'Which element represents a footer?', '<bottom>', '<footer>', '<end>', '<foot>', 'B', 'Medium', '<footer> represents footer content for a page or section.'),
('HTML', 'Which element represents navigation links?', '<navigation>', '<nav>', '<links>', '<menu>', 'B', 'Medium', '<nav> represents a section containing navigation links.'),
('HTML', 'Which element represents an independent piece of content?', '<article>', '<content>', '<post>', '<independent>', 'A', 'Medium', '<article> represents self-contained content that could be distributed independently.'),
('HTML', 'Which element represents a thematic grouping of content?', '<group>', '<section>', '<division>', '<part>', 'B', 'Medium', '<section> represents a standalone section of a document.'),
('HTML', 'Which element represents content related to the surrounding content?', '<aside>', '<side>', '<related>', '<extra>', 'A', 'Medium', '<aside> contains tangentially related content.'),
('HTML', 'Which element is commonly used for a figure or diagram?', '<image>', '<figure>', '<diagram>', '<visual>', 'B', 'Medium', '<figure> represents self-contained content such as images, diagrams, or illustrations.'),
('HTML', 'Which element provides a caption for a figure?', '<caption>', '<figcaption>', '<figure-title>', '<description>', 'B', 'Medium', '<figcaption> provides a caption for <figure> content.'),
('HTML', 'Which element is used to embed audio?', '<sound>', '<audio>', '<music>', '<media>', 'B', 'Medium', '<audio> embeds sound content.'),
('HTML', 'Which element embeds video?', '<movie>', '<media>', '<video>', '<film>', 'C', 'Medium', '<video> embeds video content.'),
('HTML', 'Which attribute displays audio/video controls?', 'buttons', 'controls', 'player', 'toolbar', 'B', 'Medium', 'controls tells the browser to display playback controls.'),
('HTML', 'Which attribute makes a video play automatically when allowed?', 'auto', 'autoplay', 'play', 'automatic', 'B', 'Medium', 'autoplay requests automatic playback, subject to browser policies.'),
('HTML', 'Which attribute makes media start over after ending?', 'repeat', 'loop', 'again', 'restart loop causes media playback to repeat.', 'B', 'Medium', 'loop causes media playback to repeat.'),
('HTML', 'Which attribute controls whether a video displays its first frame as a preview image?', 'thumbnail', 'poster', 'preview', 'cover', 'B', 'Medium', 'poster specifies an image shown while the video is unavailable or before playback.'),
('HTML', 'Which element provides multiple media resources?', '<source>', '<media-source>', '<resource>', '<src>', 'A', 'Medium', '<source> allows multiple alternative media resources.'),
('HTML', 'Which element can provide subtitles or captions for video?', '<caption>', '<track>', '<subtitle>', '<texttrack>', 'B', 'Medium', '<track> provides timed text such as subtitles, captions, and descriptions.'),
('HTML', 'Which HTML element provides a drawing surface?', '<draw>', '<canvas>', '<paint>', '<surface>', 'B', 'Medium', '<canvas> provides a scriptable bitmap drawing area.'),
('HTML', 'Which technology is commonly used with <canvas> for drawing?', 'SQL', 'JavaScript', 'PHP only', 'HTML only', 'B', 'Medium', 'JavaScript is commonly used to draw and manipulate canvas graphics.'),
('HTML', 'Which element displays scalable vector graphics directly in HTML?', '<vector>', '<svg>', '<graphics>', '<svg-image>', 'B', 'Medium', 'SVG is a markup language for scalable vector graphics.'),
('HTML', 'Which element provides responsive image sources?', '<responsive>', '<picture>', '<responsive-image>', '<imgset> <picture> allows different image sources to be selected based on conditions.', 'B', 'Medium', '<picture> allows different image sources to be selected based on conditions.'),
('HTML', 'Which attribute provides multiple image resolutions?', 'srcset', 'images', 'sources', 'resolution', 'A', 'Medium', 'srcset provides a set of image sources for different viewport or pixel-density conditions.'),
('HTML', 'Which attribute helps browsers select images based on display sizes?', 'dimensions', 'sizes', 'widths', 'screen-size', 'B', 'Medium', 'sizes gives hints about the image''s intended display size when used with srcset.'),
('HTML', 'Which element represents a date/time?', '<datetime>', '<time>', '<date>', '<timestamp>', 'B', 'Medium', '<time> represents a specific period in time or date.'),
('HTML', 'Which attribute provides a machine-readable datetime value for <time>?', 'datetime', 'value', 'datevalue', 'timevalue', 'A', 'Medium', 'The datetime attribute provides a machine-readable date/time value.'),
('HTML', 'Which element represents contact information?', '<contact>', '<address>', '<location>', '<info>', 'B', 'Medium', '<address> represents contact information for the relevant content.'),
('HTML', 'Which element represents an abbreviation?', '<abbr>', '<short>', '<acronym>', '<abbreviation>', 'A', 'Medium', '<abbr> represents an abbreviation or acronym.'),
('HTML', 'Which attribute can provide the full form of an abbreviation?', 'full', 'title', 'expand', 'meaning The title attribute can provide the expanded form.', 'B', 'Medium', 'The title attribute can provide the expanded form.'),
('HTML', 'Which element represents a citation or reference to a creative work?', '<cite>', '<reference>', '<source>', '<citation>', 'A', 'Medium', '<cite> represents the title of a cited creative work.'),
('HTML', 'Which element represents a variable?', '<var>', '<variable>', '<v>', '<value>', 'A', 'Medium', '<var> represents a variable in a mathematical or programming context.'),
('HTML', 'Which element represents sample output?', '<output>', '<samp>', '<result>', '<sample>', 'B', 'Medium', '<samp> represents sample output from a computer program.'),
('HTML', 'Which element represents keyboard input?', '<keyboard>', '<key>', '<kbd>', '<input-key>', 'C', 'Medium', '<kbd> represents user input from a keyboard or similar device.'),
('HTML', 'Which element represents a calculation result?', '<result>', '<output>', '<answer>', '<calculation>', 'B', 'Medium', '<output> represents the result of a calculation or user action.'),
('HTML', 'Which element creates a disclosure widget?', '<details>', '<disclosure>', '<collapse>', '<expand>', 'A', 'Medium', '<details> creates a disclosure widget that can be opened and closed.'),
('HTML', 'Which element provides the visible label for <details>?', '<summary>', '<label>', '<caption>', '<title>', 'A', 'Medium', '<summary> provides the visible heading for a <details> element.'),
('HTML', 'Which attribute makes <details> open by default?', 'open', 'expanded', 'show', 'visible', 'A', 'Medium', 'The Boolean open attribute makes the details content initially visible.'),
('HTML', 'Which element represents a dialog box?', '<popup>', '<dialog>', '<modal>', '<window>', 'B', 'Medium', '<dialog> represents a dialog or interactive modal-like component.'),
('HTML', 'Which element can contain navigation links as a semantic section?', '<nav>', '<navigation>', '<links>', '<menu-links>', 'A', 'Medium', '<nav> is the semantic HTML element for major navigation blocks.'),
('HTML', 'Which semantic element should generally contain the unique primary content of a page?', '<main>', '<body>', '<content>', '<section>', 'A', 'Medium', '<main> identifies the dominant content of the document.'),
('HTML', 'Which element is appropriate for a standalone blog post?', '<section>', '<article>', '<aside>', '<post>', 'B', 'Medium', 'A self-contained blog post is a good use case for <article>.'),
('HTML', 'Which element is appropriate for a sidebar?', '<side>', '<aside>', '<sidebar>', '<section-side>', 'B', 'Medium', '<aside> is commonly used for sidebars and related content.'),
('HTML', 'Which element is appropriate for a page footer?', '<bottom>', '<footer>', '<end>', '<page-end>', 'B', 'Medium', '<footer> represents footer content.'),
('HTML', 'Which HTML element is obsolete and should generally not be used for scrolling text?', '<scroll>', '<marquee>', '<moving>', '<ticker>', 'B', 'Medium', '<marquee> is obsolete and should not be used in modern HTML.'),
('HTML', 'Which tag was traditionally used to specify font styling but is obsolete?', '<font>', '<textstyle>', '<typeface>', '<face>', 'A', 'Medium', '<font> is obsolete; CSS should be used for text styling.'),
('HTML', 'Which element represents a thematic break?', '<line>', '<hr>', '<breakline>', '<separator>', 'B', 'Medium', '<hr> represents a thematic break between sections.'),
('HTML', 'Which HTML element represents an unordered collection of items?', '<ul>', '<ol>', '<items>', '<collection>', 'A', 'Medium', '<ul> represents an unordered list.'),
('HTML', 'Which element represents an ordered collection?', '<ul>', '<ol>', '<ordered>', '<sequence>', 'B', 'Medium', '<ol> represents an ordered list.'),
('HTML', 'Which element represents a line of text with strong importance?', '<b>', '<strong>', '<important>', '<bold>', 'B', 'Medium', '<strong> carries semantic meaning of strong importance.'),
('HTML', 'Which element represents stress emphasis?', '<i>', '<em>', '<italic>', '<stress>', 'B', 'Medium', '<em> represents stress emphasis.'),
('HTML', 'Which element is best for generic block-level grouping when no semantic element applies?', '<span>', '<div>', '<group>', '<block>', 'B', 'Medium', '<div> is a generic container with no inherent semantic meaning. Questions 151–200: Advanced HTML, Accessibility, SEO & APIs'),
('HTML', 'Which element is generally an inline generic container?', '<div>', '<span>', '<inline>', '<container>', 'B', 'Hard', '<span> is a generic inline container.'),
('HTML', 'Which element is generally a block-level generic container?', '<span>', '<div>', '<block>', '<container>', 'B', 'Hard', '<div> is a generic block-level container.'),
('HTML', 'Which attribute allows an element''s content to be edited by the user?', 'editable', 'contenteditable', 'edit', 'modify', 'B', 'Hard', 'contenteditable makes an element''s content editable.'),
('HTML', 'Which attribute specifies the language of an HTML document?', 'language', 'lang', 'locale', 'html-lang', 'B', 'Hard', 'The lang attribute specifies the language of an element''s content.'),
('HTML', 'Which language code represents English?', 'en', 'eng', 'english', 'EN-US-ENG', 'A', 'Hard', 'en is the standard language code for English.'),
('HTML', 'Which language code represents Marathi?', 'mr', 'mar', 'ma', 'mhr', 'A', 'Hard', 'mr is the language code for Marathi.'),
('HTML', 'Which meta tag is commonly used for character encoding?', '<meta charset="UTF-8">', '<meta encoding="UTF-8">', '<charset="UTF-8">', '<encoding="UTF-8">', 'A', 'Hard', '<meta charset="UTF-8"> declares UTF-8 character encoding.'),
('HTML', 'Which character encoding is commonly recommended for modern HTML?', 'ASCII only', 'UTF-8', 'UTF-1', 'ANSI only', 'B', 'Hard', 'UTF-8 supports a very large range of characters and is widely used on the web.'),
('HTML', 'Which meta tag helps control the viewport on mobile devices?', 'viewport', 'mobile', 'screen', 'device', 'A', 'Hard', 'The viewport meta setting controls layout behavior on mobile browsers.'),
('HTML', 'Which is a commonly used viewport declaration?', '<meta name="viewport" content="width=device-width, initial-scale=1.0">', '<meta mobile="true">', '<viewport width="device">', '<meta screen="responsive">', 'A', 'Hard', 'This declaration helps make the page responsive on mobile devices.'),
('HTML', 'What is semantic HTML?', 'HTML with only CSS', 'HTML using elements according to their meaning', 'HTML without attributes', 'HTML containing only JavaScript', 'B', 'Hard', 'Semantic HTML uses meaningful elements such as <nav>, <article>, and <footer>.'),
('HTML', 'Why is semantic HTML important?', 'It removes JavaScript', 'It improves structure, accessibility and understanding', 'It automatically adds CSS', 'It makes every website animated', 'B', 'Hard', 'Semantic markup helps browsers, assistive technologies, developers, and search engines understand content structure.'),
('HTML', 'What does accessibility in HTML primarily mean?', 'Making websites available only on mobile', 'Making websites usable by people with different abilities', 'Making websites colorful', 'Making websites load only with JavaScript', 'B', 'Hard', 'Accessibility aims to make web content usable by people with disabilities and diverse needs.'),
('HTML', 'Which attribute is especially important for providing alternative text for images?', 'src', 'alt', 'title', 'description', 'B', 'Hard', 'alt provides a text alternative for an image.'),
('HTML', 'Which attribute can hide an element semantically from normal rendering?', 'hidden', 'invisible', 'display-none', 'hide', 'A', 'Hard', 'The Boolean hidden attribute indicates that the element is not currently relevant or should not be presented.'),
('HTML', 'What is ARIA mainly used for?', 'Styling pages', 'Improving accessibility semantics when native HTML is insufficient', 'Creating databases', 'Running JavaScript', 'B', 'Hard', 'WAI-ARIA provides accessibility semantics for dynamic interfaces where native HTML alone may not communicate enough information.'),
('HTML', 'What does ARIA stand for?', 'Accessible Rich Internet Applications', 'Advanced Responsive Internet Application', 'Accessible Resource Internet API', 'Automated Rich Interface Architecture', 'A', 'Hard', 'ARIA stands for Accessible Rich Internet Applications.'),
('HTML', 'Which attribute can provide an accessible label when native visible text is unavailable?', 'aria-label', 'aria-text', 'access-label', 'label-text', 'A', 'Hard', 'aria-label provides an accessible name for an element.'),
('HTML', 'Which attribute references another element as the accessible label?', 'aria-labelledby', 'aria-labelref', 'labelled-by', 'aria-reference', 'A', 'Hard', 'aria-labelledby references the ID of an element that provides the accessible name.'),
('HTML', 'Which attribute can describe an element using another element''s content?', 'aria-describedby', 'aria-descriptionref', 'aria-help', 'description-id', 'A', 'Hard', 'aria-describedby references elements that provide additional descriptive information.'),
('HTML', 'Which element is recommended for primary navigation?', '<div>', '<nav>', '<section>', '<links>', 'B', 'Hard', '<nav> semantically identifies a navigation section.'),
('HTML', 'Which HTML element is best for a page''s primary content?', '<main>', '<section>', '<div>', '<content>', 'A', 'Hard', '<main> identifies the primary content of the page.'),
('HTML', 'Which attribute is commonly used to provide a unique hook for CSS and JavaScript?', 'id', 'unique', 'key', 'identifier', 'A', 'Hard', 'The id attribute provides a unique identifier for an element.'),
('HTML', 'Which attribute can be reused on multiple elements?', 'id', 'class', 'unique', 'identifier', 'B', 'Hard', 'The same class can be applied to multiple elements.'),
('HTML', 'Which attribute is useful for storing custom data on HTML elements?', 'custom-*', 'data-*', 'store-*', 'info-*', 'B', 'Hard', 'data-* attributes allow custom data to be associated with HTML elements.'),
('HTML', 'What is the purpose of data-* attributes?', 'To create CSS automatically', 'To store custom data associated with an element', 'To create databases', 'To replace JavaScript', 'B', 'Hard', 'Custom data attributes provide a standard way to embed application-specific data in HTML.'),
('HTML', 'Which JavaScript property commonly accesses data-user-id?', 'element.data.userId', 'element.dataset.userId', 'element.custom.userId', 'element.attribute.userId', 'B', 'Hard', 'dataset provides access to data-* attributes.'),
('HTML', 'Which element is used to define a template that is not rendered immediately?', '<template>', '<model>', '<prototype>', '<structure>', 'A', 'Hard', '<template> holds HTML that can later be instantiated using JavaScript.'),
('HTML', 'Which element is used to contain HTML that can be reused through scripting?', '<template>', '<reuse>', '<component>', '<clone>', 'A', 'Hard', '<template> is designed for reusable inert HTML fragments.'),
('HTML', 'Which HTML element can contain client-side graphics?', '<canvas>', '<draw>', '<graphic>', '<paint>', 'A', 'Hard', '<canvas> provides a drawing surface controlled by scripts.'),
('HTML', 'Which element is used to embed an external resource such as a PDF?', '<embed>', '<external>', '<resource>', '<pdf>', 'A', 'Hard', '<embed> embeds external content handled by the browser or an appropriate plugin mechanism.'),
('HTML', 'Which element can provide fallback or alternative resources for embedded media?', '<source>', '<fallback>', '<alternative>', '<resource>', 'A', 'Hard', '<source> provides alternative resources for elements such as <picture>, <audio>, and <video>.'),
('HTML', 'Which attribute allows an iframe to be restricted with security policies?', 'sandbox', 'secure', 'protect', 'restriction', 'A', 'Hard', 'The sandbox attribute applies restrictions to content inside an iframe.'),
('HTML', 'Which iframe attribute controls whether the embedded page can request fullscreen?', 'fullscreen', 'allowfullscreen', 'full-screen', 'screen-full', 'B', 'Hard', ''),
('HTML', 'Which link relation is commonly used for an external stylesheet?', 'rel="css"', 'rel="stylesheet"', 'rel="style"', 'rel="design"', 'B', 'Hard', 'rel="stylesheet" identifies the linked resource as a stylesheet.'),
('HTML', 'Which element is used to provide a favicon?', '<favicon>', '<link>', '<icon>', '<meta-icon>', 'B', 'Hard', 'A favicon is commonly referenced with a <link> element.'),
('HTML', 'Which attribute indicates that a script should execute after HTML parsing?', 'after', 'defer', 'delay', 'later', 'B', 'Hard', ''),
('HTML', 'Which script attribute allows an external script to download without blocking HTML parsing and execute when ready?', 'async', 'fast', 'parallel', 'nonblocking', 'A', 'Hard', 'async allows downloading in parallel with parsing and executes the script as soon as it is ready.'),
('HTML', 'Which attribute specifies the source file for an external JavaScript file?', 'href', 'src', 'source', 'file', 'B', 'Hard', '<script src="..."> specifies an external JavaScript file.'),
('HTML', 'Which HTML element is commonly used to include structured data in JSON-LD?', '<script>', '<json>', '<data>', '<schema>', 'A', 'Hard', 'JSON-LD structured data is commonly placed inside <script type="application/ld+json">.'),
('HTML', 'What is the main purpose of HTML in web development?', 'Database management', 'Page structure and content', 'Server hosting', 'Image editing', 'B', 'Hard', 'HTML defines the structure and meaning of web content.'),
('HTML', 'Which technology is primarily responsible for webpage styling?', 'HTML', 'CSS', 'SQL', 'JSON', 'B', 'Hard', 'CSS controls presentation, layout, and visual styling.'),
('HTML', 'Which technology is primarily used to add behavior and interactivity to webpages?', 'HTML', 'CSS', 'JavaScript', 'SQL', 'C', 'Hard', 'JavaScript is commonly used to add dynamic behavior and interactivity.'),
('HTML', 'Which HTML element contains the document metadata?', '<meta>', '<head>', '<header>', '<info>', 'B', 'Hard', 'The <head> element contains metadata and resource references.'),
('HTML', 'Which tag should normally appear only once as the primary content container?', '<main>', '<section>', '<div>', '<article>', 'A', 'Hard', 'A document generally has one primary <main> landmark.'),
('HTML', 'Which HTML feature helps search engines understand the meaning and structure of content?', 'Semantic HTML', 'Random class names', 'Inline styles', 'JavaScript variables', 'A', 'Hard', 'Semantic HTML provides meaningful structure that can help search engines interpret content.'),
('HTML', 'Which element is best suited for a standalone news story?', '<article>', '<aside>', '<nav>', '<span>', 'A', 'Hard', 'A standalone news story is appropriately represented by <article>.'),
('HTML', 'Which element is best suited for a group of navigation links?', '<nav>', '<links>', '<menu-links>', '<navigation>', 'A', 'Hard', '<nav> semantically represents navigation links.'),
('HTML', 'Which HTML element represents a generic container with no semantic meaning?', '<container>', '<div>', '<box>', '<group>', 'B', 'Hard', '<div> is a generic container used when no more meaningful semantic element applies.'),
('HTML', 'Which statement about HTML is correct?', 'HTML is a programming language', 'HTML is a markup language used to structure web content', 'HTML is a database language', 'HTML is a CSS framework', 'B', 'Hard', 'HTML is a markup language used to structure and describe content on webpages.');

-- Verification
SELECT COUNT(*) AS html_questions
FROM questions
WHERE skill = 'HTML';

SELECT COUNT(DISTINCT question) AS unique_html_questions
FROM questions
WHERE skill = 'HTML';

SELECT skill, COUNT(*) AS question_count
FROM questions
GROUP BY skill
ORDER BY skill;

DELETE FROM questions
WHERE id IN (
    SELECT id
    FROM (
        SELECT id
        FROM questions
        WHERE skill = 'JavaScript'
    ) AS temp
);

